/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.lib.soundEffect;

import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author Stefan
 */
public class PanelSound extends javax.swing.JPanel {

    public PanelSound() {
        initComponents();
    }

    public JLabel getLblSound() {
        return lblSound;
    }

    public JLabel getLblSoundOff() {
        return lblSoundOff;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSound = new javax.swing.JLabel();
        lblSoundOff = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSound.setFont(new java.awt.Font("Nirmala UI", 3, 24)); // NOI18N
        lblSound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSound.setToolTipText("");
        lblSound.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));
        add(lblSound, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        lblSoundOff.setFont(new java.awt.Font("Nirmala UI", 3, 24)); // NOI18N
        lblSoundOff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoundOff.setToolTipText("");
        lblSoundOff.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));
        add(lblSoundOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSound;
    private javax.swing.JLabel lblSoundOff;
    // End of variables declaration//GEN-END:variables

    public void getLblSoundAddMouseListener(MouseListener mouseListener) {
        lblSound.addMouseListener(mouseListener);
    }

    public void getLblSoundOffAddMouseListener(MouseListener mouseListener) {
        lblSoundOff.addMouseListener(mouseListener);
    }
}
